ARG IMAGE_TAG
FROM pizzafactory0contorno/piatto:${IMAGE_TAG}
LABEL MAINTAINER="Masaki Muranaka <monaka@pizzafactory.jp>"

USER root

RUN apk add --no-cache \
      ruby ruby-dev ruby-rake \
      gperf build-base bison flex

USER user
